name: 'NjucmSessionCheck'

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/15 * * * *'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: main
      - name: Checkout private tools
        uses: actions/checkout@v2
        with:
          repository: inokoe/vpn_sign
          token: ${{ secrets.token }}
          path: my-tools
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Install
        run: pip install requests beautifulsoup4
      - name: run
        run: python NjucmSessionCheck.py

